# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.20.30
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from clients.ctm_saas_client.configuration import Configuration


class AppPredeployResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_name': 'str',
        'ready_status': 'str'
    }

    attribute_map = {
        'app_name': 'appName',
        'ready_status': 'readyStatus'
    }

    def __init__(self, app_name=None, ready_status=None, _configuration=None):  # noqa: E501
        """AppPredeployResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._app_name = None
        self._ready_status = None
        self.discriminator = None

        if app_name is not None:
            self.app_name = app_name
        if ready_status is not None:
            self.ready_status = ready_status

    @property
    def app_name(self):
        """Gets the app_name of this AppPredeployResponse.  # noqa: E501

        app name  # noqa: E501

        :return: The app_name of this AppPredeployResponse.  # noqa: E501
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name):
        """Sets the app_name of this AppPredeployResponse.

        app name  # noqa: E501

        :param app_name: The app_name of this AppPredeployResponse.  # noqa: E501
        :type: str
        """

        self._app_name = app_name

    @property
    def ready_status(self):
        """Gets the ready_status of this AppPredeployResponse.  # noqa: E501

        ready status  # noqa: E501

        :return: The ready_status of this AppPredeployResponse.  # noqa: E501
        :rtype: str
        """
        return self._ready_status

    @ready_status.setter
    def ready_status(self, ready_status):
        """Sets the ready_status of this AppPredeployResponse.

        ready status  # noqa: E501

        :param ready_status: The ready_status of this AppPredeployResponse.  # noqa: E501
        :type: str
        """

        self._ready_status = ready_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppPredeployResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppPredeployResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AppPredeployResponse):
            return True

        return self.to_dict() != other.to_dict()
