# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.20.30
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from clients.ctm_saas_client.configuration import Configuration


class Cluster(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nodes': 'list[Node]',
        'availability': 'list[Availability]',
        'performance': 'list[Performance]'
    }

    attribute_map = {
        'nodes': 'nodes',
        'availability': 'availability',
        'performance': 'performance'
    }

    def __init__(self, nodes=None, availability=None, performance=None, _configuration=None):  # noqa: E501
        """Cluster - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._nodes = None
        self._availability = None
        self._performance = None
        self.discriminator = None

        if nodes is not None:
            self.nodes = nodes
        if availability is not None:
            self.availability = availability
        if performance is not None:
            self.performance = performance

    @property
    def nodes(self):
        """Gets the nodes of this Cluster.  # noqa: E501


        :return: The nodes of this Cluster.  # noqa: E501
        :rtype: list[Node]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this Cluster.


        :param nodes: The nodes of this Cluster.  # noqa: E501
        :type: list[Node]
        """

        self._nodes = nodes

    @property
    def availability(self):
        """Gets the availability of this Cluster.  # noqa: E501


        :return: The availability of this Cluster.  # noqa: E501
        :rtype: list[Availability]
        """
        return self._availability

    @availability.setter
    def availability(self, availability):
        """Sets the availability of this Cluster.


        :param availability: The availability of this Cluster.  # noqa: E501
        :type: list[Availability]
        """

        self._availability = availability

    @property
    def performance(self):
        """Gets the performance of this Cluster.  # noqa: E501


        :return: The performance of this Cluster.  # noqa: E501
        :rtype: list[Performance]
        """
        return self._performance

    @performance.setter
    def performance(self, performance):
        """Sets the performance of this Cluster.


        :param performance: The performance of this Cluster.  # noqa: E501
        :type: list[Performance]
        """

        self._performance = performance

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Cluster, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Cluster):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Cluster):
            return True

        return self.to_dict() != other.to_dict()
