# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class ActiveServices(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'service_last_updated_time': 'str',
        'active_services': 'list[SLAService]'
    }

    attribute_map = {
        'service_last_updated_time': 'serviceLastUpdatedTime',
        'active_services': 'activeServices'
    }

    def __init__(self, service_last_updated_time=None, active_services=None, local_vars_configuration=None):  # noqa: E501
        """ActiveServices - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._service_last_updated_time = None
        self._active_services = None
        self.discriminator = None

        if service_last_updated_time is not None:
            self.service_last_updated_time = service_last_updated_time
        if active_services is not None:
            self.active_services = active_services

    @property
    def service_last_updated_time(self):
        """Gets the service_last_updated_time of this ActiveServices.  # noqa: E501


        :return: The service_last_updated_time of this ActiveServices.  # noqa: E501
        :rtype: str
        """
        return self._service_last_updated_time

    @service_last_updated_time.setter
    def service_last_updated_time(self, service_last_updated_time):
        """Sets the service_last_updated_time of this ActiveServices.


        :param service_last_updated_time: The service_last_updated_time of this ActiveServices.  # noqa: E501
        :type service_last_updated_time: str
        """

        self._service_last_updated_time = service_last_updated_time

    @property
    def active_services(self):
        """Gets the active_services of this ActiveServices.  # noqa: E501


        :return: The active_services of this ActiveServices.  # noqa: E501
        :rtype: list[SLAService]
        """
        return self._active_services

    @active_services.setter
    def active_services(self, active_services):
        """Sets the active_services of this ActiveServices.


        :param active_services: The active_services of this ActiveServices.  # noqa: E501
        :type active_services: list[SLAService]
        """

        self._active_services = active_services

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActiveServices):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ActiveServices):
            return True

        return self.to_dict() != other.to_dict()
