# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class AllMFTDataSettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'settings': 'list[SettingProperties]',
        'settings_metadata': 'SettingsMetadataProperties'
    }

    attribute_map = {
        'settings': 'settings',
        'settings_metadata': 'settingsMetadata'
    }

    def __init__(self, settings=None, settings_metadata=None, local_vars_configuration=None):  # noqa: E501
        """AllMFTDataSettings - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._settings = None
        self._settings_metadata = None
        self.discriminator = None

        if settings is not None:
            self.settings = settings
        if settings_metadata is not None:
            self.settings_metadata = settings_metadata

    @property
    def settings(self):
        """Gets the settings of this AllMFTDataSettings.  # noqa: E501


        :return: The settings of this AllMFTDataSettings.  # noqa: E501
        :rtype: list[SettingProperties]
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this AllMFTDataSettings.


        :param settings: The settings of this AllMFTDataSettings.  # noqa: E501
        :type settings: list[SettingProperties]
        """

        self._settings = settings

    @property
    def settings_metadata(self):
        """Gets the settings_metadata of this AllMFTDataSettings.  # noqa: E501


        :return: The settings_metadata of this AllMFTDataSettings.  # noqa: E501
        :rtype: SettingsMetadataProperties
        """
        return self._settings_metadata

    @settings_metadata.setter
    def settings_metadata(self, settings_metadata):
        """Sets the settings_metadata of this AllMFTDataSettings.


        :param settings_metadata: The settings_metadata of this AllMFTDataSettings.  # noqa: E501
        :type settings_metadata: SettingsMetadataProperties
        """

        self._settings_metadata = settings_metadata

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllMFTDataSettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AllMFTDataSettings):
            return True

        return self.to_dict() != other.to_dict()
