# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class AuthorizeSSHData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'associated_agent': 'str',
        'physical_host': 'str'
    }

    attribute_map = {
        'associated_agent': 'associatedAgent',
        'physical_host': 'physicalHost'
    }

    def __init__(self, associated_agent=None, physical_host=None, local_vars_configuration=None):  # noqa: E501
        """AuthorizeSSHData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._associated_agent = None
        self._physical_host = None
        self.discriminator = None

        if associated_agent is not None:
            self.associated_agent = associated_agent
        if physical_host is not None:
            self.physical_host = physical_host

    @property
    def associated_agent(self):
        """Gets the associated_agent of this AuthorizeSSHData.  # noqa: E501

        Optionally case insensitive agent name of host or alias of the Agent.  # noqa: E501

        :return: The associated_agent of this AuthorizeSSHData.  # noqa: E501
        :rtype: str
        """
        return self._associated_agent

    @associated_agent.setter
    def associated_agent(self, associated_agent):
        """Sets the associated_agent of this AuthorizeSSHData.

        Optionally case insensitive agent name of host or alias of the Agent.  # noqa: E501

        :param associated_agent: The associated_agent of this AuthorizeSSHData.  # noqa: E501
        :type associated_agent: str
        """

        self._associated_agent = associated_agent

    @property
    def physical_host(self):
        """Gets the physical_host of this AuthorizeSSHData.  # noqa: E501

        Optionally case insensitive logical name.  # noqa: E501

        :return: The physical_host of this AuthorizeSSHData.  # noqa: E501
        :rtype: str
        """
        return self._physical_host

    @physical_host.setter
    def physical_host(self, physical_host):
        """Sets the physical_host of this AuthorizeSSHData.

        Optionally case insensitive logical name.  # noqa: E501

        :param physical_host: The physical_host of this AuthorizeSSHData.  # noqa: E501
        :type physical_host: str
        """

        self._physical_host = physical_host

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorizeSSHData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AuthorizeSSHData):
            return True

        return self.to_dict() != other.to_dict()
