# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class CtmAddonActivation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'enabled': 'bool',
        'addon_name': 'str'
    }

    attribute_map = {
        'enabled': 'enabled',
        'addon_name': 'addonName'
    }

    def __init__(self, enabled=None, addon_name=None, local_vars_configuration=None):  # noqa: E501
        """CtmAddonActivation - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._enabled = None
        self._addon_name = None
        self.discriminator = None

        if enabled is not None:
            self.enabled = enabled
        if addon_name is not None:
            self.addon_name = addon_name

    @property
    def enabled(self):
        """Gets the enabled of this CtmAddonActivation.  # noqa: E501

        Indicates whether the add-on is enabled  # noqa: E501

        :return: The enabled of this CtmAddonActivation.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this CtmAddonActivation.

        Indicates whether the add-on is enabled  # noqa: E501

        :param enabled: The enabled of this CtmAddonActivation.  # noqa: E501
        :type enabled: bool
        """

        self._enabled = enabled

    @property
    def addon_name(self):
        """Gets the addon_name of this CtmAddonActivation.  # noqa: E501

        addon name  # noqa: E501

        :return: The addon_name of this CtmAddonActivation.  # noqa: E501
        :rtype: str
        """
        return self._addon_name

    @addon_name.setter
    def addon_name(self, addon_name):
        """Sets the addon_name of this CtmAddonActivation.

        addon name  # noqa: E501

        :param addon_name: The addon_name of this CtmAddonActivation.  # noqa: E501
        :type addon_name: str
        """

        self._addon_name = addon_name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CtmAddonActivation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CtmAddonActivation):
            return True

        return self.to_dict() != other.to_dict()
