# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class Event(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'ctm': 'str',
        'date': 'str'
    }

    attribute_map = {
        'name': 'name',
        'ctm': 'ctm',
        'date': 'date'
    }

    def __init__(self, name=None, ctm=None, date=None, local_vars_configuration=None):  # noqa: E501
        """Event - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._ctm = None
        self._date = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if ctm is not None:
            self.ctm = ctm
        if date is not None:
            self.date = date

    @property
    def name(self):
        """Gets the name of this Event.  # noqa: E501

        Event name  # noqa: E501

        :return: The name of this Event.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Event.

        Event name  # noqa: E501

        :param name: The name of this Event.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def ctm(self):
        """Gets the ctm of this Event.  # noqa: E501

        Control-M Server hosting the event  # noqa: E501

        :return: The ctm of this Event.  # noqa: E501
        :rtype: str
        """
        return self._ctm

    @ctm.setter
    def ctm(self, ctm):
        """Sets the ctm of this Event.

        Control-M Server hosting the event  # noqa: E501

        :param ctm: The ctm of this Event.  # noqa: E501
        :type ctm: str
        """

        self._ctm = ctm

    @property
    def date(self):
        """Gets the date of this Event.  # noqa: E501

        The event date, either date in format dd/mm/yy or a string \"orderdate\"  # noqa: E501

        :return: The date of this Event.  # noqa: E501
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this Event.

        The event date, either date in format dd/mm/yy or a string \"orderdate\"  # noqa: E501

        :param date: The date of this Event.  # noqa: E501
        :type date: str
        """

        self._date = date

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Event):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Event):
            return True

        return self.to_dict() != other.to_dict()
