# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class FieldMetadataProperties(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'control_type': 'str',
        'data_type': 'str',
        'display_name': 'str',
        'display_name_id': 'str',
        'false_value': 'str',
        'hashed_password': 'bool',
        'hide_if': 'ConditionProperties',
        'key': 'SettingKeyProperties',
        'name': 'str',
        'need_restart': 'bool',
        'read_only': 'bool',
        'copy_tooltip': 'str',
        'copied_tooltip': 'str',
        'need_restart_message': 'str',
        'need_restart_message_id': 'str',
        'placeholder': 'str',
        'placeholder_id': 'str',
        'possible_values': 'list[PossibleValueProperties]',
        'profiles': 'list[str]',
        'setting_changed_event_types': 'list[str]',
        'show_if': 'ConditionProperties',
        'tooltip': 'str',
        'tooltip_id': 'str',
        'true_value': 'str',
        'units_label': 'str',
        'units_label_id': 'str',
        'validations': 'ValidationProperties',
        'operation_link_label': 'str',
        'current_label': 'str',
        'new_label': 'str',
        'warning_title': 'str',
        'warning_message': 'str',
        'operation_button_label': 'str',
        'operation_cancel_button_label': 'str',
        'operation_discard_link_label': 'str',
        'rows_number': 'int',
        'prevent_line_break': 'bool',
        'prevent_resize': 'bool',
        'allow_exceed_length': 'bool'
    }

    attribute_map = {
        'control_type': 'controlType',
        'data_type': 'dataType',
        'display_name': 'displayName',
        'display_name_id': 'displayNameID',
        'false_value': 'falseValue',
        'hashed_password': 'hashedPassword',
        'hide_if': 'hideIf',
        'key': 'key',
        'name': 'name',
        'need_restart': 'needRestart',
        'read_only': 'readOnly',
        'copy_tooltip': 'copyTooltip',
        'copied_tooltip': 'copiedTooltip',
        'need_restart_message': 'needRestartMessage',
        'need_restart_message_id': 'needRestartMessageID',
        'placeholder': 'placeholder',
        'placeholder_id': 'placeholderID',
        'possible_values': 'possibleValues',
        'profiles': 'profiles',
        'setting_changed_event_types': 'settingChangedEventTypes',
        'show_if': 'showIf',
        'tooltip': 'tooltip',
        'tooltip_id': 'tooltipID',
        'true_value': 'trueValue',
        'units_label': 'unitsLabel',
        'units_label_id': 'unitsLabelID',
        'validations': 'validations',
        'operation_link_label': 'operationLinkLabel',
        'current_label': 'currentLabel',
        'new_label': 'newLabel',
        'warning_title': 'warningTitle',
        'warning_message': 'warningMessage',
        'operation_button_label': 'operationButtonLabel',
        'operation_cancel_button_label': 'operationCancelButtonLabel',
        'operation_discard_link_label': 'operationDiscardLinkLabel',
        'rows_number': 'rowsNumber',
        'prevent_line_break': 'preventLineBreak',
        'prevent_resize': 'preventResize',
        'allow_exceed_length': 'allowExceedLength'
    }

    def __init__(self, control_type=None, data_type=None, display_name=None, display_name_id=None, false_value=None, hashed_password=None, hide_if=None, key=None, name=None, need_restart=None, read_only=None, copy_tooltip=None, copied_tooltip=None, need_restart_message=None, need_restart_message_id=None, placeholder=None, placeholder_id=None, possible_values=None, profiles=None, setting_changed_event_types=None, show_if=None, tooltip=None, tooltip_id=None, true_value=None, units_label=None, units_label_id=None, validations=None, operation_link_label=None, current_label=None, new_label=None, warning_title=None, warning_message=None, operation_button_label=None, operation_cancel_button_label=None, operation_discard_link_label=None, rows_number=None, prevent_line_break=None, prevent_resize=None, allow_exceed_length=None, local_vars_configuration=None):  # noqa: E501
        """FieldMetadataProperties - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._control_type = None
        self._data_type = None
        self._display_name = None
        self._display_name_id = None
        self._false_value = None
        self._hashed_password = None
        self._hide_if = None
        self._key = None
        self._name = None
        self._need_restart = None
        self._read_only = None
        self._copy_tooltip = None
        self._copied_tooltip = None
        self._need_restart_message = None
        self._need_restart_message_id = None
        self._placeholder = None
        self._placeholder_id = None
        self._possible_values = None
        self._profiles = None
        self._setting_changed_event_types = None
        self._show_if = None
        self._tooltip = None
        self._tooltip_id = None
        self._true_value = None
        self._units_label = None
        self._units_label_id = None
        self._validations = None
        self._operation_link_label = None
        self._current_label = None
        self._new_label = None
        self._warning_title = None
        self._warning_message = None
        self._operation_button_label = None
        self._operation_cancel_button_label = None
        self._operation_discard_link_label = None
        self._rows_number = None
        self._prevent_line_break = None
        self._prevent_resize = None
        self._allow_exceed_length = None
        self.discriminator = None

        if control_type is not None:
            self.control_type = control_type
        if data_type is not None:
            self.data_type = data_type
        if display_name is not None:
            self.display_name = display_name
        if display_name_id is not None:
            self.display_name_id = display_name_id
        if false_value is not None:
            self.false_value = false_value
        if hashed_password is not None:
            self.hashed_password = hashed_password
        if hide_if is not None:
            self.hide_if = hide_if
        if key is not None:
            self.key = key
        if name is not None:
            self.name = name
        if need_restart is not None:
            self.need_restart = need_restart
        if read_only is not None:
            self.read_only = read_only
        if copy_tooltip is not None:
            self.copy_tooltip = copy_tooltip
        if copied_tooltip is not None:
            self.copied_tooltip = copied_tooltip
        if need_restart_message is not None:
            self.need_restart_message = need_restart_message
        if need_restart_message_id is not None:
            self.need_restart_message_id = need_restart_message_id
        if placeholder is not None:
            self.placeholder = placeholder
        if placeholder_id is not None:
            self.placeholder_id = placeholder_id
        if possible_values is not None:
            self.possible_values = possible_values
        if profiles is not None:
            self.profiles = profiles
        if setting_changed_event_types is not None:
            self.setting_changed_event_types = setting_changed_event_types
        if show_if is not None:
            self.show_if = show_if
        if tooltip is not None:
            self.tooltip = tooltip
        if tooltip_id is not None:
            self.tooltip_id = tooltip_id
        if true_value is not None:
            self.true_value = true_value
        if units_label is not None:
            self.units_label = units_label
        if units_label_id is not None:
            self.units_label_id = units_label_id
        if validations is not None:
            self.validations = validations
        if operation_link_label is not None:
            self.operation_link_label = operation_link_label
        if current_label is not None:
            self.current_label = current_label
        if new_label is not None:
            self.new_label = new_label
        if warning_title is not None:
            self.warning_title = warning_title
        if warning_message is not None:
            self.warning_message = warning_message
        if operation_button_label is not None:
            self.operation_button_label = operation_button_label
        if operation_cancel_button_label is not None:
            self.operation_cancel_button_label = operation_cancel_button_label
        if operation_discard_link_label is not None:
            self.operation_discard_link_label = operation_discard_link_label
        if rows_number is not None:
            self.rows_number = rows_number
        if prevent_line_break is not None:
            self.prevent_line_break = prevent_line_break
        if prevent_resize is not None:
            self.prevent_resize = prevent_resize
        if allow_exceed_length is not None:
            self.allow_exceed_length = allow_exceed_length

    @property
    def control_type(self):
        """Gets the control_type of this FieldMetadataProperties.  # noqa: E501


        :return: The control_type of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._control_type

    @control_type.setter
    def control_type(self, control_type):
        """Sets the control_type of this FieldMetadataProperties.


        :param control_type: The control_type of this FieldMetadataProperties.  # noqa: E501
        :type control_type: str
        """

        self._control_type = control_type

    @property
    def data_type(self):
        """Gets the data_type of this FieldMetadataProperties.  # noqa: E501


        :return: The data_type of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this FieldMetadataProperties.


        :param data_type: The data_type of this FieldMetadataProperties.  # noqa: E501
        :type data_type: str
        """

        self._data_type = data_type

    @property
    def display_name(self):
        """Gets the display_name of this FieldMetadataProperties.  # noqa: E501


        :return: The display_name of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this FieldMetadataProperties.


        :param display_name: The display_name of this FieldMetadataProperties.  # noqa: E501
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def display_name_id(self):
        """Gets the display_name_id of this FieldMetadataProperties.  # noqa: E501


        :return: The display_name_id of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._display_name_id

    @display_name_id.setter
    def display_name_id(self, display_name_id):
        """Sets the display_name_id of this FieldMetadataProperties.


        :param display_name_id: The display_name_id of this FieldMetadataProperties.  # noqa: E501
        :type display_name_id: str
        """

        self._display_name_id = display_name_id

    @property
    def false_value(self):
        """Gets the false_value of this FieldMetadataProperties.  # noqa: E501


        :return: The false_value of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._false_value

    @false_value.setter
    def false_value(self, false_value):
        """Sets the false_value of this FieldMetadataProperties.


        :param false_value: The false_value of this FieldMetadataProperties.  # noqa: E501
        :type false_value: str
        """

        self._false_value = false_value

    @property
    def hashed_password(self):
        """Gets the hashed_password of this FieldMetadataProperties.  # noqa: E501


        :return: The hashed_password of this FieldMetadataProperties.  # noqa: E501
        :rtype: bool
        """
        return self._hashed_password

    @hashed_password.setter
    def hashed_password(self, hashed_password):
        """Sets the hashed_password of this FieldMetadataProperties.


        :param hashed_password: The hashed_password of this FieldMetadataProperties.  # noqa: E501
        :type hashed_password: bool
        """

        self._hashed_password = hashed_password

    @property
    def hide_if(self):
        """Gets the hide_if of this FieldMetadataProperties.  # noqa: E501


        :return: The hide_if of this FieldMetadataProperties.  # noqa: E501
        :rtype: ConditionProperties
        """
        return self._hide_if

    @hide_if.setter
    def hide_if(self, hide_if):
        """Sets the hide_if of this FieldMetadataProperties.


        :param hide_if: The hide_if of this FieldMetadataProperties.  # noqa: E501
        :type hide_if: ConditionProperties
        """

        self._hide_if = hide_if

    @property
    def key(self):
        """Gets the key of this FieldMetadataProperties.  # noqa: E501


        :return: The key of this FieldMetadataProperties.  # noqa: E501
        :rtype: SettingKeyProperties
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this FieldMetadataProperties.


        :param key: The key of this FieldMetadataProperties.  # noqa: E501
        :type key: SettingKeyProperties
        """

        self._key = key

    @property
    def name(self):
        """Gets the name of this FieldMetadataProperties.  # noqa: E501


        :return: The name of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FieldMetadataProperties.


        :param name: The name of this FieldMetadataProperties.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def need_restart(self):
        """Gets the need_restart of this FieldMetadataProperties.  # noqa: E501


        :return: The need_restart of this FieldMetadataProperties.  # noqa: E501
        :rtype: bool
        """
        return self._need_restart

    @need_restart.setter
    def need_restart(self, need_restart):
        """Sets the need_restart of this FieldMetadataProperties.


        :param need_restart: The need_restart of this FieldMetadataProperties.  # noqa: E501
        :type need_restart: bool
        """

        self._need_restart = need_restart

    @property
    def read_only(self):
        """Gets the read_only of this FieldMetadataProperties.  # noqa: E501


        :return: The read_only of this FieldMetadataProperties.  # noqa: E501
        :rtype: bool
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only):
        """Sets the read_only of this FieldMetadataProperties.


        :param read_only: The read_only of this FieldMetadataProperties.  # noqa: E501
        :type read_only: bool
        """

        self._read_only = read_only

    @property
    def copy_tooltip(self):
        """Gets the copy_tooltip of this FieldMetadataProperties.  # noqa: E501


        :return: The copy_tooltip of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._copy_tooltip

    @copy_tooltip.setter
    def copy_tooltip(self, copy_tooltip):
        """Sets the copy_tooltip of this FieldMetadataProperties.


        :param copy_tooltip: The copy_tooltip of this FieldMetadataProperties.  # noqa: E501
        :type copy_tooltip: str
        """

        self._copy_tooltip = copy_tooltip

    @property
    def copied_tooltip(self):
        """Gets the copied_tooltip of this FieldMetadataProperties.  # noqa: E501


        :return: The copied_tooltip of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._copied_tooltip

    @copied_tooltip.setter
    def copied_tooltip(self, copied_tooltip):
        """Sets the copied_tooltip of this FieldMetadataProperties.


        :param copied_tooltip: The copied_tooltip of this FieldMetadataProperties.  # noqa: E501
        :type copied_tooltip: str
        """

        self._copied_tooltip = copied_tooltip

    @property
    def need_restart_message(self):
        """Gets the need_restart_message of this FieldMetadataProperties.  # noqa: E501


        :return: The need_restart_message of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._need_restart_message

    @need_restart_message.setter
    def need_restart_message(self, need_restart_message):
        """Sets the need_restart_message of this FieldMetadataProperties.


        :param need_restart_message: The need_restart_message of this FieldMetadataProperties.  # noqa: E501
        :type need_restart_message: str
        """

        self._need_restart_message = need_restart_message

    @property
    def need_restart_message_id(self):
        """Gets the need_restart_message_id of this FieldMetadataProperties.  # noqa: E501


        :return: The need_restart_message_id of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._need_restart_message_id

    @need_restart_message_id.setter
    def need_restart_message_id(self, need_restart_message_id):
        """Sets the need_restart_message_id of this FieldMetadataProperties.


        :param need_restart_message_id: The need_restart_message_id of this FieldMetadataProperties.  # noqa: E501
        :type need_restart_message_id: str
        """

        self._need_restart_message_id = need_restart_message_id

    @property
    def placeholder(self):
        """Gets the placeholder of this FieldMetadataProperties.  # noqa: E501


        :return: The placeholder of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._placeholder

    @placeholder.setter
    def placeholder(self, placeholder):
        """Sets the placeholder of this FieldMetadataProperties.


        :param placeholder: The placeholder of this FieldMetadataProperties.  # noqa: E501
        :type placeholder: str
        """

        self._placeholder = placeholder

    @property
    def placeholder_id(self):
        """Gets the placeholder_id of this FieldMetadataProperties.  # noqa: E501


        :return: The placeholder_id of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._placeholder_id

    @placeholder_id.setter
    def placeholder_id(self, placeholder_id):
        """Sets the placeholder_id of this FieldMetadataProperties.


        :param placeholder_id: The placeholder_id of this FieldMetadataProperties.  # noqa: E501
        :type placeholder_id: str
        """

        self._placeholder_id = placeholder_id

    @property
    def possible_values(self):
        """Gets the possible_values of this FieldMetadataProperties.  # noqa: E501


        :return: The possible_values of this FieldMetadataProperties.  # noqa: E501
        :rtype: list[PossibleValueProperties]
        """
        return self._possible_values

    @possible_values.setter
    def possible_values(self, possible_values):
        """Sets the possible_values of this FieldMetadataProperties.


        :param possible_values: The possible_values of this FieldMetadataProperties.  # noqa: E501
        :type possible_values: list[PossibleValueProperties]
        """

        self._possible_values = possible_values

    @property
    def profiles(self):
        """Gets the profiles of this FieldMetadataProperties.  # noqa: E501


        :return: The profiles of this FieldMetadataProperties.  # noqa: E501
        :rtype: list[str]
        """
        return self._profiles

    @profiles.setter
    def profiles(self, profiles):
        """Sets the profiles of this FieldMetadataProperties.


        :param profiles: The profiles of this FieldMetadataProperties.  # noqa: E501
        :type profiles: list[str]
        """

        self._profiles = profiles

    @property
    def setting_changed_event_types(self):
        """Gets the setting_changed_event_types of this FieldMetadataProperties.  # noqa: E501


        :return: The setting_changed_event_types of this FieldMetadataProperties.  # noqa: E501
        :rtype: list[str]
        """
        return self._setting_changed_event_types

    @setting_changed_event_types.setter
    def setting_changed_event_types(self, setting_changed_event_types):
        """Sets the setting_changed_event_types of this FieldMetadataProperties.


        :param setting_changed_event_types: The setting_changed_event_types of this FieldMetadataProperties.  # noqa: E501
        :type setting_changed_event_types: list[str]
        """

        self._setting_changed_event_types = setting_changed_event_types

    @property
    def show_if(self):
        """Gets the show_if of this FieldMetadataProperties.  # noqa: E501


        :return: The show_if of this FieldMetadataProperties.  # noqa: E501
        :rtype: ConditionProperties
        """
        return self._show_if

    @show_if.setter
    def show_if(self, show_if):
        """Sets the show_if of this FieldMetadataProperties.


        :param show_if: The show_if of this FieldMetadataProperties.  # noqa: E501
        :type show_if: ConditionProperties
        """

        self._show_if = show_if

    @property
    def tooltip(self):
        """Gets the tooltip of this FieldMetadataProperties.  # noqa: E501


        :return: The tooltip of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._tooltip

    @tooltip.setter
    def tooltip(self, tooltip):
        """Sets the tooltip of this FieldMetadataProperties.


        :param tooltip: The tooltip of this FieldMetadataProperties.  # noqa: E501
        :type tooltip: str
        """

        self._tooltip = tooltip

    @property
    def tooltip_id(self):
        """Gets the tooltip_id of this FieldMetadataProperties.  # noqa: E501


        :return: The tooltip_id of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._tooltip_id

    @tooltip_id.setter
    def tooltip_id(self, tooltip_id):
        """Sets the tooltip_id of this FieldMetadataProperties.


        :param tooltip_id: The tooltip_id of this FieldMetadataProperties.  # noqa: E501
        :type tooltip_id: str
        """

        self._tooltip_id = tooltip_id

    @property
    def true_value(self):
        """Gets the true_value of this FieldMetadataProperties.  # noqa: E501


        :return: The true_value of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._true_value

    @true_value.setter
    def true_value(self, true_value):
        """Sets the true_value of this FieldMetadataProperties.


        :param true_value: The true_value of this FieldMetadataProperties.  # noqa: E501
        :type true_value: str
        """

        self._true_value = true_value

    @property
    def units_label(self):
        """Gets the units_label of this FieldMetadataProperties.  # noqa: E501


        :return: The units_label of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._units_label

    @units_label.setter
    def units_label(self, units_label):
        """Sets the units_label of this FieldMetadataProperties.


        :param units_label: The units_label of this FieldMetadataProperties.  # noqa: E501
        :type units_label: str
        """

        self._units_label = units_label

    @property
    def units_label_id(self):
        """Gets the units_label_id of this FieldMetadataProperties.  # noqa: E501


        :return: The units_label_id of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._units_label_id

    @units_label_id.setter
    def units_label_id(self, units_label_id):
        """Sets the units_label_id of this FieldMetadataProperties.


        :param units_label_id: The units_label_id of this FieldMetadataProperties.  # noqa: E501
        :type units_label_id: str
        """

        self._units_label_id = units_label_id

    @property
    def validations(self):
        """Gets the validations of this FieldMetadataProperties.  # noqa: E501


        :return: The validations of this FieldMetadataProperties.  # noqa: E501
        :rtype: ValidationProperties
        """
        return self._validations

    @validations.setter
    def validations(self, validations):
        """Sets the validations of this FieldMetadataProperties.


        :param validations: The validations of this FieldMetadataProperties.  # noqa: E501
        :type validations: ValidationProperties
        """

        self._validations = validations

    @property
    def operation_link_label(self):
        """Gets the operation_link_label of this FieldMetadataProperties.  # noqa: E501


        :return: The operation_link_label of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._operation_link_label

    @operation_link_label.setter
    def operation_link_label(self, operation_link_label):
        """Sets the operation_link_label of this FieldMetadataProperties.


        :param operation_link_label: The operation_link_label of this FieldMetadataProperties.  # noqa: E501
        :type operation_link_label: str
        """

        self._operation_link_label = operation_link_label

    @property
    def current_label(self):
        """Gets the current_label of this FieldMetadataProperties.  # noqa: E501


        :return: The current_label of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._current_label

    @current_label.setter
    def current_label(self, current_label):
        """Sets the current_label of this FieldMetadataProperties.


        :param current_label: The current_label of this FieldMetadataProperties.  # noqa: E501
        :type current_label: str
        """

        self._current_label = current_label

    @property
    def new_label(self):
        """Gets the new_label of this FieldMetadataProperties.  # noqa: E501


        :return: The new_label of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._new_label

    @new_label.setter
    def new_label(self, new_label):
        """Sets the new_label of this FieldMetadataProperties.


        :param new_label: The new_label of this FieldMetadataProperties.  # noqa: E501
        :type new_label: str
        """

        self._new_label = new_label

    @property
    def warning_title(self):
        """Gets the warning_title of this FieldMetadataProperties.  # noqa: E501


        :return: The warning_title of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._warning_title

    @warning_title.setter
    def warning_title(self, warning_title):
        """Sets the warning_title of this FieldMetadataProperties.


        :param warning_title: The warning_title of this FieldMetadataProperties.  # noqa: E501
        :type warning_title: str
        """

        self._warning_title = warning_title

    @property
    def warning_message(self):
        """Gets the warning_message of this FieldMetadataProperties.  # noqa: E501


        :return: The warning_message of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._warning_message

    @warning_message.setter
    def warning_message(self, warning_message):
        """Sets the warning_message of this FieldMetadataProperties.


        :param warning_message: The warning_message of this FieldMetadataProperties.  # noqa: E501
        :type warning_message: str
        """

        self._warning_message = warning_message

    @property
    def operation_button_label(self):
        """Gets the operation_button_label of this FieldMetadataProperties.  # noqa: E501


        :return: The operation_button_label of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._operation_button_label

    @operation_button_label.setter
    def operation_button_label(self, operation_button_label):
        """Sets the operation_button_label of this FieldMetadataProperties.


        :param operation_button_label: The operation_button_label of this FieldMetadataProperties.  # noqa: E501
        :type operation_button_label: str
        """

        self._operation_button_label = operation_button_label

    @property
    def operation_cancel_button_label(self):
        """Gets the operation_cancel_button_label of this FieldMetadataProperties.  # noqa: E501


        :return: The operation_cancel_button_label of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._operation_cancel_button_label

    @operation_cancel_button_label.setter
    def operation_cancel_button_label(self, operation_cancel_button_label):
        """Sets the operation_cancel_button_label of this FieldMetadataProperties.


        :param operation_cancel_button_label: The operation_cancel_button_label of this FieldMetadataProperties.  # noqa: E501
        :type operation_cancel_button_label: str
        """

        self._operation_cancel_button_label = operation_cancel_button_label

    @property
    def operation_discard_link_label(self):
        """Gets the operation_discard_link_label of this FieldMetadataProperties.  # noqa: E501


        :return: The operation_discard_link_label of this FieldMetadataProperties.  # noqa: E501
        :rtype: str
        """
        return self._operation_discard_link_label

    @operation_discard_link_label.setter
    def operation_discard_link_label(self, operation_discard_link_label):
        """Sets the operation_discard_link_label of this FieldMetadataProperties.


        :param operation_discard_link_label: The operation_discard_link_label of this FieldMetadataProperties.  # noqa: E501
        :type operation_discard_link_label: str
        """

        self._operation_discard_link_label = operation_discard_link_label

    @property
    def rows_number(self):
        """Gets the rows_number of this FieldMetadataProperties.  # noqa: E501


        :return: The rows_number of this FieldMetadataProperties.  # noqa: E501
        :rtype: int
        """
        return self._rows_number

    @rows_number.setter
    def rows_number(self, rows_number):
        """Sets the rows_number of this FieldMetadataProperties.


        :param rows_number: The rows_number of this FieldMetadataProperties.  # noqa: E501
        :type rows_number: int
        """

        self._rows_number = rows_number

    @property
    def prevent_line_break(self):
        """Gets the prevent_line_break of this FieldMetadataProperties.  # noqa: E501


        :return: The prevent_line_break of this FieldMetadataProperties.  # noqa: E501
        :rtype: bool
        """
        return self._prevent_line_break

    @prevent_line_break.setter
    def prevent_line_break(self, prevent_line_break):
        """Sets the prevent_line_break of this FieldMetadataProperties.


        :param prevent_line_break: The prevent_line_break of this FieldMetadataProperties.  # noqa: E501
        :type prevent_line_break: bool
        """

        self._prevent_line_break = prevent_line_break

    @property
    def prevent_resize(self):
        """Gets the prevent_resize of this FieldMetadataProperties.  # noqa: E501


        :return: The prevent_resize of this FieldMetadataProperties.  # noqa: E501
        :rtype: bool
        """
        return self._prevent_resize

    @prevent_resize.setter
    def prevent_resize(self, prevent_resize):
        """Sets the prevent_resize of this FieldMetadataProperties.


        :param prevent_resize: The prevent_resize of this FieldMetadataProperties.  # noqa: E501
        :type prevent_resize: bool
        """

        self._prevent_resize = prevent_resize

    @property
    def allow_exceed_length(self):
        """Gets the allow_exceed_length of this FieldMetadataProperties.  # noqa: E501


        :return: The allow_exceed_length of this FieldMetadataProperties.  # noqa: E501
        :rtype: bool
        """
        return self._allow_exceed_length

    @allow_exceed_length.setter
    def allow_exceed_length(self, allow_exceed_length):
        """Sets the allow_exceed_length of this FieldMetadataProperties.


        :param allow_exceed_length: The allow_exceed_length of this FieldMetadataProperties.  # noqa: E501
        :type allow_exceed_length: bool
        """

        self._allow_exceed_length = allow_exceed_length

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldMetadataProperties):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FieldMetadataProperties):
            return True

        return self.to_dict() != other.to_dict()
