# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class HostgroupProperties(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'agentslist': 'list[AgentInGroupParams]',
        'application_type': 'str',
        'tag': 'str'
    }

    attribute_map = {
        'agentslist': 'agentslist',
        'application_type': 'applicationType',
        'tag': 'tag'
    }

    def __init__(self, agentslist=None, application_type=None, tag=None, local_vars_configuration=None):  # noqa: E501
        """HostgroupProperties - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._agentslist = None
        self._application_type = None
        self._tag = None
        self.discriminator = None

        if agentslist is not None:
            self.agentslist = agentslist
        if application_type is not None:
            self.application_type = application_type
        if tag is not None:
            self.tag = tag

    @property
    def agentslist(self):
        """Gets the agentslist of this HostgroupProperties.  # noqa: E501

        Agents list. HIDDEN.  # noqa: E501

        :return: The agentslist of this HostgroupProperties.  # noqa: E501
        :rtype: list[AgentInGroupParams]
        """
        return self._agentslist

    @agentslist.setter
    def agentslist(self, agentslist):
        """Sets the agentslist of this HostgroupProperties.

        Agents list. HIDDEN.  # noqa: E501

        :param agentslist: The agentslist of this HostgroupProperties.  # noqa: E501
        :type agentslist: list[AgentInGroupParams]
        """

        self._agentslist = agentslist

    @property
    def application_type(self):
        """Gets the application_type of this HostgroupProperties.  # noqa: E501

        Host Group application type. HIDDEN.  # noqa: E501

        :return: The application_type of this HostgroupProperties.  # noqa: E501
        :rtype: str
        """
        return self._application_type

    @application_type.setter
    def application_type(self, application_type):
        """Sets the application_type of this HostgroupProperties.

        Host Group application type. HIDDEN.  # noqa: E501

        :param application_type: The application_type of this HostgroupProperties.  # noqa: E501
        :type application_type: str
        """

        self._application_type = application_type

    @property
    def tag(self):
        """Gets the tag of this HostgroupProperties.  # noqa: E501

        Host Group tag. HIDDEN.  # noqa: E501

        :return: The tag of this HostgroupProperties.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this HostgroupProperties.

        Host Group tag. HIDDEN.  # noqa: E501

        :param tag: The tag of this HostgroupProperties.  # noqa: E501
        :type tag: str
        """

        self._tag = tag

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostgroupProperties):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HostgroupProperties):
            return True

        return self.to_dict() != other.to_dict()
