# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class JobtypeAgent(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'server': 'str',
        'agent': 'str'
    }

    attribute_map = {
        'server': 'server',
        'agent': 'agent'
    }

    def __init__(self, server=None, agent=None, local_vars_configuration=None):  # noqa: E501
        """JobtypeAgent - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._server = None
        self._agent = None
        self.discriminator = None

        if server is not None:
            self.server = server
        if agent is not None:
            self.agent = agent

    @property
    def server(self):
        """Gets the server of this JobtypeAgent.  # noqa: E501

        Server name  # noqa: E501

        :return: The server of this JobtypeAgent.  # noqa: E501
        :rtype: str
        """
        return self._server

    @server.setter
    def server(self, server):
        """Sets the server of this JobtypeAgent.

        Server name  # noqa: E501

        :param server: The server of this JobtypeAgent.  # noqa: E501
        :type server: str
        """

        self._server = server

    @property
    def agent(self):
        """Gets the agent of this JobtypeAgent.  # noqa: E501

        Agent name  # noqa: E501

        :return: The agent of this JobtypeAgent.  # noqa: E501
        :rtype: str
        """
        return self._agent

    @agent.setter
    def agent(self, agent):
        """Sets the agent of this JobtypeAgent.

        Agent name  # noqa: E501

        :param agent: The agent of this JobtypeAgent.  # noqa: E501
        :type agent: str
        """

        self._agent = agent

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobtypeAgent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JobtypeAgent):
            return True

        return self.to_dict() != other.to_dict()
