# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class MfteDbConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'mfte_db_host1': 'str',
        'mfte_db_port1': 'int',
        'mfte_db_name': 'str',
        'mfte_db_user': 'str',
        'mfte_db_password': 'str',
        'mfte_db_host2': 'str',
        'mfte_db_port2': 'int',
        'db_type': 'str'
    }

    attribute_map = {
        'mfte_db_host1': 'mfteDbHost1',
        'mfte_db_port1': 'mfteDbPort1',
        'mfte_db_name': 'mfteDbName',
        'mfte_db_user': 'mfteDbUser',
        'mfte_db_password': 'mfteDbPassword',
        'mfte_db_host2': 'mfteDbHost2',
        'mfte_db_port2': 'mfteDbPort2',
        'db_type': 'dbType'
    }

    def __init__(self, mfte_db_host1=None, mfte_db_port1=None, mfte_db_name=None, mfte_db_user=None, mfte_db_password=None, mfte_db_host2=None, mfte_db_port2=None, db_type=None, local_vars_configuration=None):  # noqa: E501
        """MfteDbConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._mfte_db_host1 = None
        self._mfte_db_port1 = None
        self._mfte_db_name = None
        self._mfte_db_user = None
        self._mfte_db_password = None
        self._mfte_db_host2 = None
        self._mfte_db_port2 = None
        self._db_type = None
        self.discriminator = None

        if mfte_db_host1 is not None:
            self.mfte_db_host1 = mfte_db_host1
        if mfte_db_port1 is not None:
            self.mfte_db_port1 = mfte_db_port1
        if mfte_db_name is not None:
            self.mfte_db_name = mfte_db_name
        if mfte_db_user is not None:
            self.mfte_db_user = mfte_db_user
        if mfte_db_password is not None:
            self.mfte_db_password = mfte_db_password
        if mfte_db_host2 is not None:
            self.mfte_db_host2 = mfte_db_host2
        if mfte_db_port2 is not None:
            self.mfte_db_port2 = mfte_db_port2
        if db_type is not None:
            self.db_type = db_type

    @property
    def mfte_db_host1(self):
        """Gets the mfte_db_host1 of this MfteDbConfig.  # noqa: E501

        Defines the database server host 1 HIDDEN  # noqa: E501

        :return: The mfte_db_host1 of this MfteDbConfig.  # noqa: E501
        :rtype: str
        """
        return self._mfte_db_host1

    @mfte_db_host1.setter
    def mfte_db_host1(self, mfte_db_host1):
        """Sets the mfte_db_host1 of this MfteDbConfig.

        Defines the database server host 1 HIDDEN  # noqa: E501

        :param mfte_db_host1: The mfte_db_host1 of this MfteDbConfig.  # noqa: E501
        :type mfte_db_host1: str
        """

        self._mfte_db_host1 = mfte_db_host1

    @property
    def mfte_db_port1(self):
        """Gets the mfte_db_port1 of this MfteDbConfig.  # noqa: E501

        Defines the database server port 1 HIDDEN  # noqa: E501

        :return: The mfte_db_port1 of this MfteDbConfig.  # noqa: E501
        :rtype: int
        """
        return self._mfte_db_port1

    @mfte_db_port1.setter
    def mfte_db_port1(self, mfte_db_port1):
        """Sets the mfte_db_port1 of this MfteDbConfig.

        Defines the database server port 1 HIDDEN  # noqa: E501

        :param mfte_db_port1: The mfte_db_port1 of this MfteDbConfig.  # noqa: E501
        :type mfte_db_port1: int
        """

        self._mfte_db_port1 = mfte_db_port1

    @property
    def mfte_db_name(self):
        """Gets the mfte_db_name of this MfteDbConfig.  # noqa: E501

        Defines the database schema name HIDDEN  # noqa: E501

        :return: The mfte_db_name of this MfteDbConfig.  # noqa: E501
        :rtype: str
        """
        return self._mfte_db_name

    @mfte_db_name.setter
    def mfte_db_name(self, mfte_db_name):
        """Sets the mfte_db_name of this MfteDbConfig.

        Defines the database schema name HIDDEN  # noqa: E501

        :param mfte_db_name: The mfte_db_name of this MfteDbConfig.  # noqa: E501
        :type mfte_db_name: str
        """

        self._mfte_db_name = mfte_db_name

    @property
    def mfte_db_user(self):
        """Gets the mfte_db_user of this MfteDbConfig.  # noqa: E501

        Defines the MFTE database user name HIDDEN  # noqa: E501

        :return: The mfte_db_user of this MfteDbConfig.  # noqa: E501
        :rtype: str
        """
        return self._mfte_db_user

    @mfte_db_user.setter
    def mfte_db_user(self, mfte_db_user):
        """Sets the mfte_db_user of this MfteDbConfig.

        Defines the MFTE database user name HIDDEN  # noqa: E501

        :param mfte_db_user: The mfte_db_user of this MfteDbConfig.  # noqa: E501
        :type mfte_db_user: str
        """

        self._mfte_db_user = mfte_db_user

    @property
    def mfte_db_password(self):
        """Gets the mfte_db_password of this MfteDbConfig.  # noqa: E501

        Defines the MFTE database password HIDDEN  # noqa: E501

        :return: The mfte_db_password of this MfteDbConfig.  # noqa: E501
        :rtype: str
        """
        return self._mfte_db_password

    @mfte_db_password.setter
    def mfte_db_password(self, mfte_db_password):
        """Sets the mfte_db_password of this MfteDbConfig.

        Defines the MFTE database password HIDDEN  # noqa: E501

        :param mfte_db_password: The mfte_db_password of this MfteDbConfig.  # noqa: E501
        :type mfte_db_password: str
        """

        self._mfte_db_password = mfte_db_password

    @property
    def mfte_db_host2(self):
        """Gets the mfte_db_host2 of this MfteDbConfig.  # noqa: E501

        Defines the database server host 2 HIDDEN  # noqa: E501

        :return: The mfte_db_host2 of this MfteDbConfig.  # noqa: E501
        :rtype: str
        """
        return self._mfte_db_host2

    @mfte_db_host2.setter
    def mfte_db_host2(self, mfte_db_host2):
        """Sets the mfte_db_host2 of this MfteDbConfig.

        Defines the database server host 2 HIDDEN  # noqa: E501

        :param mfte_db_host2: The mfte_db_host2 of this MfteDbConfig.  # noqa: E501
        :type mfte_db_host2: str
        """

        self._mfte_db_host2 = mfte_db_host2

    @property
    def mfte_db_port2(self):
        """Gets the mfte_db_port2 of this MfteDbConfig.  # noqa: E501

        Defines the database server host 2 HIDDEN  # noqa: E501

        :return: The mfte_db_port2 of this MfteDbConfig.  # noqa: E501
        :rtype: int
        """
        return self._mfte_db_port2

    @mfte_db_port2.setter
    def mfte_db_port2(self, mfte_db_port2):
        """Sets the mfte_db_port2 of this MfteDbConfig.

        Defines the database server host 2 HIDDEN  # noqa: E501

        :param mfte_db_port2: The mfte_db_port2 of this MfteDbConfig.  # noqa: E501
        :type mfte_db_port2: int
        """

        self._mfte_db_port2 = mfte_db_port2

    @property
    def db_type(self):
        """Gets the db_type of this MfteDbConfig.  # noqa: E501

        Defines the database type HIDDEN  # noqa: E501

        :return: The db_type of this MfteDbConfig.  # noqa: E501
        :rtype: str
        """
        return self._db_type

    @db_type.setter
    def db_type(self, db_type):
        """Sets the db_type of this MfteDbConfig.

        Defines the database type HIDDEN  # noqa: E501

        :param db_type: The db_type of this MfteDbConfig.  # noqa: E501
        :type db_type: str
        """

        self._db_type = db_type

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MfteDbConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MfteDbConfig):
            return True

        return self.to_dict() != other.to_dict()
