# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class PoolVariablesName(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'pool_name': 'str',
        'variable_name': 'list[str]'
    }

    attribute_map = {
        'pool_name': 'pool_name',
        'variable_name': 'variable_name'
    }

    def __init__(self, pool_name=None, variable_name=None, local_vars_configuration=None):  # noqa: E501
        """PoolVariablesName - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._pool_name = None
        self._variable_name = None
        self.discriminator = None

        if pool_name is not None:
            self.pool_name = pool_name
        if variable_name is not None:
            self.variable_name = variable_name

    @property
    def pool_name(self):
        """Gets the pool_name of this PoolVariablesName.  # noqa: E501


        :return: The pool_name of this PoolVariablesName.  # noqa: E501
        :rtype: str
        """
        return self._pool_name

    @pool_name.setter
    def pool_name(self, pool_name):
        """Sets the pool_name of this PoolVariablesName.


        :param pool_name: The pool_name of this PoolVariablesName.  # noqa: E501
        :type pool_name: str
        """

        self._pool_name = pool_name

    @property
    def variable_name(self):
        """Gets the variable_name of this PoolVariablesName.  # noqa: E501


        :return: The variable_name of this PoolVariablesName.  # noqa: E501
        :rtype: list[str]
        """
        return self._variable_name

    @variable_name.setter
    def variable_name(self, variable_name):
        """Sets the variable_name of this PoolVariablesName.


        :param variable_name: The variable_name of this PoolVariablesName.  # noqa: E501
        :type variable_name: list[str]
        """

        self._variable_name = variable_name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoolVariablesName):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PoolVariablesName):
            return True

        return self.to_dict() != other.to_dict()
