# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class RulesStatisticListSummary(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'rules_statistic_list': 'RulesStatisticList',
        'summary': 'Summary'
    }

    attribute_map = {
        'rules_statistic_list': 'rulesStatisticList',
        'summary': 'summary'
    }

    def __init__(self, rules_statistic_list=None, summary=None, local_vars_configuration=None):  # noqa: E501
        """RulesStatisticListSummary - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._rules_statistic_list = None
        self._summary = None
        self.discriminator = None

        if rules_statistic_list is not None:
            self.rules_statistic_list = rules_statistic_list
        if summary is not None:
            self.summary = summary

    @property
    def rules_statistic_list(self):
        """Gets the rules_statistic_list of this RulesStatisticListSummary.  # noqa: E501


        :return: The rules_statistic_list of this RulesStatisticListSummary.  # noqa: E501
        :rtype: RulesStatisticList
        """
        return self._rules_statistic_list

    @rules_statistic_list.setter
    def rules_statistic_list(self, rules_statistic_list):
        """Sets the rules_statistic_list of this RulesStatisticListSummary.


        :param rules_statistic_list: The rules_statistic_list of this RulesStatisticListSummary.  # noqa: E501
        :type rules_statistic_list: RulesStatisticList
        """

        self._rules_statistic_list = rules_statistic_list

    @property
    def summary(self):
        """Gets the summary of this RulesStatisticListSummary.  # noqa: E501


        :return: The summary of this RulesStatisticListSummary.  # noqa: E501
        :rtype: Summary
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this RulesStatisticListSummary.


        :param summary: The summary of this RulesStatisticListSummary.  # noqa: E501
        :type summary: Summary
        """

        self._summary = summary

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RulesStatisticListSummary):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RulesStatisticListSummary):
            return True

        return self.to_dict() != other.to_dict()
