# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class RunReportInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'report_id': 'str',
        'name': 'str',
        'format': 'str',
        'status': 'str',
        'url': 'str',
        'web_url': 'str'
    }

    attribute_map = {
        'report_id': 'reportId',
        'name': 'name',
        'format': 'format',
        'status': 'status',
        'url': 'url',
        'web_url': 'webUrl'
    }

    def __init__(self, report_id=None, name=None, format=None, status=None, url=None, web_url=None, local_vars_configuration=None):  # noqa: E501
        """RunReportInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._report_id = None
        self._name = None
        self._format = None
        self._status = None
        self._url = None
        self._web_url = None
        self.discriminator = None

        self.report_id = report_id
        self.name = name
        self.format = format
        self.status = status
        self.url = url
        self.web_url = web_url

    @property
    def report_id(self):
        """Gets the report_id of this RunReportInfo.  # noqa: E501


        :return: The report_id of this RunReportInfo.  # noqa: E501
        :rtype: str
        """
        return self._report_id

    @report_id.setter
    def report_id(self, report_id):
        """Sets the report_id of this RunReportInfo.


        :param report_id: The report_id of this RunReportInfo.  # noqa: E501
        :type report_id: str
        """

        self._report_id = report_id

    @property
    def name(self):
        """Gets the name of this RunReportInfo.  # noqa: E501


        :return: The name of this RunReportInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RunReportInfo.


        :param name: The name of this RunReportInfo.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def format(self):
        """Gets the format of this RunReportInfo.  # noqa: E501


        :return: The format of this RunReportInfo.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this RunReportInfo.


        :param format: The format of this RunReportInfo.  # noqa: E501
        :type format: str
        """

        self._format = format

    @property
    def status(self):
        """Gets the status of this RunReportInfo.  # noqa: E501


        :return: The status of this RunReportInfo.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this RunReportInfo.


        :param status: The status of this RunReportInfo.  # noqa: E501
        :type status: str
        """

        self._status = status

    @property
    def url(self):
        """Gets the url of this RunReportInfo.  # noqa: E501


        :return: The url of this RunReportInfo.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this RunReportInfo.


        :param url: The url of this RunReportInfo.  # noqa: E501
        :type url: str
        """

        self._url = url

    @property
    def web_url(self):
        """Gets the web_url of this RunReportInfo.  # noqa: E501


        :return: The web_url of this RunReportInfo.  # noqa: E501
        :rtype: str
        """
        return self._web_url

    @web_url.setter
    def web_url(self, web_url):
        """Sets the web_url of this RunReportInfo.


        :param web_url: The web_url of this RunReportInfo.  # noqa: E501
        :type web_url: str
        """

        self._web_url = web_url

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunReportInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RunReportInfo):
            return True

        return self.to_dict() != other.to_dict()
