# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class ShoutDestinationList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'shout_destinations': 'list[ShoutDestination]'
    }

    attribute_map = {
        'name': 'name',
        'shout_destinations': 'shoutDestinations'
    }

    def __init__(self, name=None, shout_destinations=None, local_vars_configuration=None):  # noqa: E501
        """ShoutDestinationList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._shout_destinations = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if shout_destinations is not None:
            self.shout_destinations = shout_destinations

    @property
    def name(self):
        """Gets the name of this ShoutDestinationList.  # noqa: E501

        Shout Destination List name  # noqa: E501

        :return: The name of this ShoutDestinationList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ShoutDestinationList.

        Shout Destination List name  # noqa: E501

        :param name: The name of this ShoutDestinationList.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def shout_destinations(self):
        """Gets the shout_destinations of this ShoutDestinationList.  # noqa: E501

        Shout Destinations  # noqa: E501

        :return: The shout_destinations of this ShoutDestinationList.  # noqa: E501
        :rtype: list[ShoutDestination]
        """
        return self._shout_destinations

    @shout_destinations.setter
    def shout_destinations(self, shout_destinations):
        """Sets the shout_destinations of this ShoutDestinationList.

        Shout Destinations  # noqa: E501

        :param shout_destinations: The shout_destinations of this ShoutDestinationList.  # noqa: E501
        :type shout_destinations: list[ShoutDestination]
        """

        self._shout_destinations = shout_destinations

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShoutDestinationList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ShoutDestinationList):
            return True

        return self.to_dict() != other.to_dict()
