# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class UnOrderedJobsList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'folder_name': 'str',
        'job_name': 'str'
    }

    attribute_map = {
        'folder_name': 'folderName',
        'job_name': 'jobName'
    }

    def __init__(self, folder_name=None, job_name=None, local_vars_configuration=None):  # noqa: E501
        """UnOrderedJobsList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._folder_name = None
        self._job_name = None
        self.discriminator = None

        if folder_name is not None:
            self.folder_name = folder_name
        if job_name is not None:
            self.job_name = job_name

    @property
    def folder_name(self):
        """Gets the folder_name of this UnOrderedJobsList.  # noqa: E501


        :return: The folder_name of this UnOrderedJobsList.  # noqa: E501
        :rtype: str
        """
        return self._folder_name

    @folder_name.setter
    def folder_name(self, folder_name):
        """Sets the folder_name of this UnOrderedJobsList.


        :param folder_name: The folder_name of this UnOrderedJobsList.  # noqa: E501
        :type folder_name: str
        """

        self._folder_name = folder_name

    @property
    def job_name(self):
        """Gets the job_name of this UnOrderedJobsList.  # noqa: E501


        :return: The job_name of this UnOrderedJobsList.  # noqa: E501
        :rtype: str
        """
        return self._job_name

    @job_name.setter
    def job_name(self, job_name):
        """Sets the job_name of this UnOrderedJobsList.


        :param job_name: The job_name of this UnOrderedJobsList.  # noqa: E501
        :type job_name: str
        """

        self._job_name = job_name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnOrderedJobsList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UnOrderedJobsList):
            return True

        return self.to_dict() != other.to_dict()
