# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    The version of the OpenAPI document: 9.22.30
    Contact: customer_support@bmc.com
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from clients.ctm_api_client.configuration import Configuration


class UserConditionData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'company_names': 'list[str]',
        'user_or_group_names': 'list[str]'
    }

    attribute_map = {
        'company_names': 'companyNames',
        'user_or_group_names': 'userOrGroupNames'
    }

    def __init__(self, company_names=None, user_or_group_names=None, local_vars_configuration=None):  # noqa: E501
        """UserConditionData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._company_names = None
        self._user_or_group_names = None
        self.discriminator = None

        if company_names is not None:
            self.company_names = company_names
        if user_or_group_names is not None:
            self.user_or_group_names = user_or_group_names

    @property
    def company_names(self):
        """Gets the company_names of this UserConditionData.  # noqa: E501

        array of company names  # noqa: E501

        :return: The company_names of this UserConditionData.  # noqa: E501
        :rtype: list[str]
        """
        return self._company_names

    @company_names.setter
    def company_names(self, company_names):
        """Sets the company_names of this UserConditionData.

        array of company names  # noqa: E501

        :param company_names: The company_names of this UserConditionData.  # noqa: E501
        :type company_names: list[str]
        """

        self._company_names = company_names

    @property
    def user_or_group_names(self):
        """Gets the user_or_group_names of this UserConditionData.  # noqa: E501

        array of user or group names  # noqa: E501

        :return: The user_or_group_names of this UserConditionData.  # noqa: E501
        :rtype: list[str]
        """
        return self._user_or_group_names

    @user_or_group_names.setter
    def user_or_group_names(self, user_or_group_names):
        """Sets the user_or_group_names of this UserConditionData.

        array of user or group names  # noqa: E501

        :param user_or_group_names: The user_or_group_names of this UserConditionData.  # noqa: E501
        :type user_or_group_names: list[str]
        """

        self._user_or_group_names = user_or_group_names

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserConditionData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserConditionData):
            return True

        return self.to_dict() != other.to_dict()
